//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontV3.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guitar
    {
        public int GuitarID { get; set; }
        public string GuitarModel { get; set; }
        public string GuitarDescription { get; set; }
        public string GuitarImage { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public Nullable<int> UnitsOnOrder { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<int> BrandID { get; set; }
        public int GuitarInventoryID { get; set; }
        public int GuitarCategory { get; set; }
        public int DeptID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Department Department { get; set; }
        public virtual Guitar_Category Guitar_Category { get; set; }
        public virtual GuitarInventory GuitarInventory { get; set; }
    }
}
